stages:
    - lint
    - build
    - publish

licenses_checker:
    stage: lint
    image: registry.gitlab.com/ai-r/cogment/license-checker:latest
    script:
        - license-checker

shellcheck:
    image: koalaman/shellcheck-alpine:stable
    stage: lint
    before_script:
        - shellcheck --version
    script:
        - shellcheck $(find . -name '*.sh' | xargs)

shfmt:
    image: mvdan/shfmt:v3.7.0-alpine
    stage: lint
    before_script:
        - shfmt --version
    script:
        - shfmt -d .

.base:
    image: python:3.10
    variables:
        PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    before_script:
        - mkdir -p ${PIP_CACHE_DIR}
        - python -m venv .venv
        - source .venv/bin/activate
        - pip install --upgrade pip
        - pip install -e .[dev]
    cache:
        - paths:
              - .cache/pip
        - key:
              files:
                  - requirements.txt
                  - setup.cfg
          paths:
              - ".venv"

build_sdist:
    extends: .base
    stage: build
    script:
        - hatch build
    artifacts:
        expire_in: 1 week
        paths:
            - dist/*.tar.gz
            - dist/*.whl

publish_to_pypi:
    extends: .base
    stage: publish
    needs:
        - build_sdist
    script:
        - hatch publish -u $PYPI_USERNAME -a $PYPI_PASSWORD
    rules:
        - if: $CI_COMMIT_TAG
