name: build
on: [pull_request, push]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build-all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v3
      - run: |
           docker build -f bin/all-py.Dockerfile \
             --build-arg PYTHON_VERSION=${{ matrix.python-version }} \
             --tag cogment_lab-all-docker .
      - name: Start background services
        run: docker run -d --name cogment_lab-test cogment_lab-all-docker /usr/local/bin/cogmentlab launch base

      - name: Run tests
        run: docker run cogment_lab-all-docker pytest tests/*


  build-necessary:
    runs-on:
      ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
           docker build -f bin/necessary-py.Dockerfile \
             --build-arg PYTHON_VERSION='3.10' \
             --tag cogment_lab-necessary-docker .
      - name: Run tests
        run: |
           docker run cogment_lab-necessary-docker pytest tests
